import { Open_Sans } from "next/font/google";
import localFont from 'next/font/local'

import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import "./globals.css";

import Header from '@/app/_components/header';
import Footer from '@/app/_components/footer';
import Transition from '@/app/_components/page-transition';

const openSans = Open_Sans({ subsets: ['latin'], variable: '--font-open-sans' });


const halyard = localFont({
  src: [
    {
      path: '../../public/fonts/Halyard/Halyard_Display_Light.otf',
      weight: '300'
    },
    {
      path: '../../public/fonts/Halyard/Halyard_Display_Book.otf',
      weight: '400'
    },
    {
      path: '../../public/fonts/Halyard/Halyard_Display_Regular.otf',
      weight: '500'
    },
    {
      path: '../../public/fonts/Halyard/Halyard_Display.otf',
      weight: '600'
    }
  ],
  variable: '--font-halyard'
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body className={`${halyard.variable} ${openSans.variable} font-sans font-normal bg-white h-screen flex flex-col`}>
        <Header />
        <Transition>
          {children}
        </Transition>
        <Footer />
      </body>
    </html>
  );
}
